font_family      family="NotoSansM Nerd Font Mono"
bold_font        family='NotoSansM Nerd Font Mono' style='Bold'
italic_font      family='NotoSansM Nerd Font Mono' style='Condensed Light'
bold_italic_font family='NotoSansM Nerd Font Mono' style='Condensed ExtraBold'

font_size 10.0

disable_ligatures always

cursor_trail 1

mouse_hide_wait 0

underline_hyperlinks always

paste_actions quote-urls-at-prompt,confirm,confirm-if-large

remember_window_size  no
initial_window_width  120c
initial_window_height 810

enabled_layouts splits,grid,stack

draw_minimal_borders no

single_window_margin_width 1

window_padding_width 1.5

confirm_os_window_close -3 count-background

tab_bar_edge top

tab_bar_margin_height 0.0 1.0

tab_bar_style powerline

tab_switch_strategy left

tab_powerline_style slanted

foreground #e3e3e3
background #0b0015

background_image /home/jacob/Pictures/Terminal Background.png

background_image_layout clamped

selection_foreground #0b0015
selection_background #e3e3e3

color0 #141414
color8 #7f8c8d

color1 #ed1515
color9 #ff0000

color2  #27d132
color10 #04dc00

color3  #ffcb0e
color11 #ffff00

color4  #2175f3
color12 #0066ff

color5  #9737e1
color13 #b700ff

color6  #09dacc
color14 #00ffff

color7  #dfdfdf
color15 #ffffff

notify_on_cmd_finish unfocused

map kitty_mod+8 launch --location=vsplit
map kitty_mod+9 launch --location=hsplit
map kitty_mod+0 launch --location=split

map kitty_mod+left neighboring_window left
map kitty_mod+right neighboring_window right

map kitty_mod+up neighboring_window up
map kitty_mod+down neighboring_window down

map ctrl+up move_window up
map ctrl+left move_window left
map ctrl+right move_window right
map ctrl+down move_window down
