#!/usr/bin/env zsh

update-djn() {
  if ! command -v arch-news-checker-djn &> /dev/null; then
    echo "arch-news-checker-djn is not installed. Please install it first." >&2
    return 1
  fi

  arch-news-checker-djn -c
  local news_status="$?"
  if (( news_status == 0 )); then
    # Remove Rust bin (from rustup) from PATH to prevent potential issues
    local OLD_PATH="$PATH"
    local rust_bin="$HOME/.cargo/bin"
    if [[ "$PATH" == *"$rust_bin"* ]]; then
      PATH="${PATH//$rust_bin:}"
      PATH="${PATH//:$rust_bin}"
    fi

    # Update the system
    printf "\n-- \e[1m\e[4mSystem Update\e[0m --\n"
    if ! sudo pacman -Syu; then
      echo "System update failed. Aborting AUR update."
      PATH="$OLD_PATH"
      return 1
    fi
    printf "\n-- \e[1m\e[4mAUR Update\e[0m --\n"
    paru -Syu

    # Restore the original PATH
    PATH="$OLD_PATH"
  elif (( news_status == 2 )); then
    echo "There are new Arch Linux news items. Please read them before updating. (arch-news-checker-djn -h)"
    return 1
  else
    echo "There was an issue fetching the news. Aborting system update."
    return 1
  fi
}
